spring.application.name=ip-check-api

spring.profiles.active=dev

springdoc.swagger-ui.path=/docs

ip-intelligence.provider=mock
ip-intelligence.base-url=https://proxycheck.io/v2
ip-intelligence.api-key=${IP_INTELLIGENCE_API_KEY:}
ip-intelligence.cache-duration-minutes=60

ip-import.max-csv-file-size-bytes=1048576