spring.application.name=ip-check-api

spring.datasource.url=jdbc:h2:mem:ipcheckdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/docs

ip-intelligence.provider=proxycheck
ip-intelligence.base-url=https://proxycheck.io/v2
ip-intelligence.api-key=${IP_INTELLIGENCE_API_KEY:}